- hosts: all
  sudo: True
  
  tasks:
    - name: Creates destination directory
      file: state=directory mode=0700 dest=/root/.ssh/
      
    - name: Pushes user's rsa key to root's (it's ok if this TASK fails)
      action: copy src=~/.ssh/id_rsa.pub dest=/root/.ssh/authorized_keys owner=root mode=0600
      register: rsa
      ignore_errors: yes

    - name: Pushes user's dsa key to root's (it's NOT ok if both TASKs fail)
      action: copy src=~/.ssh/id_dsa.pub dest=/root/.ssh/authorized_keys owner=root mode=0600
      when: rsa|failed

    - name: Checks if resolver is working properly (issues with some VBox/Host OS combinations)
      action: command host -t A ansible.cc
      register: ns
      ignore_errors: yes

    - name: Pushes new resolver configuration is resolver fails
      action: lineinfile regexp="^nameserver " line="nameserver 8.8.8.8" dest=/etc/resolv.conf
      when: ns|failed

    - name: Checks if resolver is working properly with new nameserver
      action: command host -t A ansible.cc

    - name: Final greeting
      action: pause prompt="Don't worry about all the red above; if you made it here, your Vagrant VMs are probably fine !
        Please press [Enter]"
